// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAtqgWcbUqfmSWE_fcKBGsGyU_OF-bRWU',
    appId: '1:1002848135869:web:798b2ed8217da0e46d25d4',
    messagingSenderId: '1002848135869',
    projectId: 'elctronic-68b6c',
    authDomain: 'elctronic-68b6c.firebaseapp.com',
    storageBucket: 'elctronic-68b6c.firebasestorage.app',
    measurementId: 'G-HW6YS1NNR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbf95rH6Zci6aDMIoGoIZk58ib8b28Fi4',
    appId: '1:1002848135869:android:0b28e4ef8bb0547f6d25d4',
    messagingSenderId: '1002848135869',
    projectId: 'elctronic-68b6c',
    storageBucket: 'elctronic-68b6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqR7txup3wE15AZSkJzX5_5uV81tW5iXM',
    appId: '1:1002848135869:ios:e09d467e8d6dd4976d25d4',
    messagingSenderId: '1002848135869',
    projectId: 'elctronic-68b6c',
    storageBucket: 'elctronic-68b6c.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqR7txup3wE15AZSkJzX5_5uV81tW5iXM',
    appId: '1:1002848135869:ios:e09d467e8d6dd4976d25d4',
    messagingSenderId: '1002848135869',
    projectId: 'elctronic-68b6c',
    storageBucket: 'elctronic-68b6c.firebasestorage.app',
    iosBundleId: 'com.example.assignment1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAtqgWcbUqfmSWE_fcKBGsGyU_OF-bRWU',
    appId: '1:1002848135869:web:21d13c7d96030c966d25d4',
    messagingSenderId: '1002848135869',
    projectId: 'elctronic-68b6c',
    authDomain: 'elctronic-68b6c.firebaseapp.com',
    storageBucket: 'elctronic-68b6c.firebasestorage.app',
    measurementId: 'G-KD4V28HDEL',
  );
}
